# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# coverage configuration
coverage:
  range: 70..90
  round: down
  precision: 3
  status:
    project:
      default:
        target: 75
        threshold: 5

ignore:
  - "**/autotest/*"
  - "**/examples/*"
  - "**/sandbox/*"
  - "**/scripts/*"
  - "**/src/*/bench/*"
  - "**/src/*/tests/*"

# parse coverage reports
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

