# 
# Makefile for modem module
#


local_dir	:= src/modem
local_lib	:= libmodem.a
local_src	:= \
	src/modem.c \
	src/modem_create.c \
	src/modem_common.c \
	src/modulate.c \
	src/demodulate.c

# accumulate
libraries	+= $(local_lib)
sources		+= $(local_src)

include ../../common.mk
